added Junit + docker deployment

diff --git a/.github/workflows/build_server.yml b/.github/workflows/build_server.yml
--- a/.github/workflows/build_server.yml
+++ b/.github/workflows/build_server.yml
@@ -1,4 +1,4 @@
-name: Bit mentor telegram bot
+name: Bit mentor telegram server
 
 on:
   push:
@@ -12,7 +12,9 @@ permissions:
 jobs:
   build:
     runs-on: ubuntu-latest
-
+    permissions:
+      checks: write
+      
     steps:
     - uses: actions/checkout@v4
 
@@ -32,7 +34,7 @@ jobs:
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
 
-    - name: Test with pytest
+    - name: create .env_dev file
       run: |
         echo "OPENAI_KEY_DEV=${{ secrets.OPENAI_KEY_DEV }}" >> .env_dev
         echo "DATABASE_NAME_DEV=${{ secrets.DATABASE_NAME_DEV }}" >> .env_dev
@@ -43,4 +45,60 @@ jobs:
         echo "MOTIVATION_API_DEV=${{ secrets.MOTIVATION_API_DEV }}" >> .env_dev
         echo "YOUTUBE_API_DEV=${{ secrets.YOUTUBE_API_DEV }}" >> .env_dev
         echo "MONGO_CONNECTION_STRING_DEV=${{ secrets.MONGO_CONNECTION_STRING_DEV }}" >> .env_dev
-        pytest
+
+    - name: Test with pytest
+      env:
+        ENVIRONMENT: dev
+      run: |
+        python -m pytest --verbose --junit-xml=junit.xml
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/junit.xml'
+        detailed_summary: true
+        include_passed: true
+
+
+  docker_deploy:
+    runs-on: ubuntu-latest
+    needs: build
+
+    steps:
+    - name: Install Docker
+      run: |
+        sudo apt-get update
+        sudo apt-get install ca-certificates curl
+        sudo install -m 0755 -d /etc/apt/keyrings
+        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
+        sudo chmod a+r /etc/apt/keyrings/docker.asc
+
+        # Add the repository to Apt sources:
+        echo \
+          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
+          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
+          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+        sudo apt-get update
+        sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
+
+
+    - name: Start Docker service
+      run: |
+        sudo systemctl start docker
+        sudo systemctl enable docker
+
+    - name: Check Docker and Docker Compose versions
+      run: |
+        docker --version
+        docker-compose --version
+
+    - name: Log in to Docker Hub
+      run: |
+        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
+
+    - name: Docker Deployment
+      run: |
+        echo "Running Docker deployment..."
+        ./docker-deploy.sh ${{ secrets.DOCKER_HUB_USERNAME }} dev
+
+
